package com.example.myapplication.utils

import com.example.myapplication.R


//MAIN ACTIVITY AND FRAGMENT
const val MAIN_TAG = "MAIN_TAG"

//CONNECTION FRAGMENT
const val JOHN_DOE_ID = 0
const val USER_ID = 1

//CREATE USER FRAGMENT
const val MENU_TAG = "MENU_TAG"
const val REPORT_TAG = "REPORT_TAG"
const val REGISTRATION_TAG = "REGISTRATION_TAG"
const val REGISTRATION_CREATE_USER_TAG = "REGISTRATION_CREATE_USER_TAG"
const val REGISTRATION_UPDATE_USER_TAG = "REGISTRATION_UPDATE_USER_TAG"
const val GRV_CONTROL_TAG = "GRV_CONTROL_TAG"

const val CHECK_GRV = "CHECK_GRV"
const val PERF_GRV = "PERF_GRV"

const val PERIODIC_GRV_REPORT = "PERIODIC_GRV_REPORT "
const val ADR_GRV_REPORT = "ADR_GRV_REPORT "
