package com.example.domain.model

data class BusinessRemoteGRVControlStep(
    val step: Int,
    val commandeUid: Int,
    val reference: Int,
    val reportNumber: Int? = null,
    val customer: String? = null,
    val customerSerialNumber: String? = null,
    val serialNumberAlorem: String? = null,
    val type: String? = null,
    val fabricationPlateAdr: Boolean? = null,
    val aloremPlate: Boolean? = null,
    val bookletPouch: Boolean? = null,
    val userManual: Boolean? = null,
    val instructionOfUse: Boolean? = null,
    val certificatesADR: Boolean? = null,
    val groundingAdhesive: Boolean? = null,
    val conformityCertificateMarking: Boolean? = null,
    val marquePrincipale: String? = null,
    val tare: Int? = null,
    val material: String? = null,
    val capacity20: Int? = null,
    val grossMass: Int? = null,
    val fabricationDate: String? = null,
    val shellThickness: Int? = null,
    val pictogramStacking: Boolean? = null,
    val weightStacking: Int? = null,
    val bottomRetentionFace: Int? = null,
    val bottomRetentionRight: Int? = null,
    val bottomRetentionLeft: Int? = null,
    val bottomRetentionBehind: Int? = null,
    val upperRetention: Int? = null,
    val liftingRings: Int? = null,
    val forkliftPass: Int? = null,
    val dashboard: Int? = null,
    val unauthorizedRepair: Boolean? = null,
    val internalNA: Boolean? = null,
    val internalOK: Boolean? = null,
    val internalClean: Boolean? = null,
    val internalObjectInside: Boolean? = null,
    val internalPollution: Boolean? = null,
    val epaisseurNA: Boolean? = null,
    val epaisseurMinSideFront: Int? = null,
    val epaisseurMinSideBack: Int? = null,
    val epaisseurMinSideRight: Int? = null,
    val epaisseurMinSideLeft: Int? = null,
    val epaisseurSideFrontResult1: Int? = null,
    val epaisseurSideFrontResult2: Int? = null,
    val epaisseurSideFrontResult3: Int? = null,
    val epaisseurSideFrontResult4: Int? = null,
    val epaisseurSideFrontResult5: Int? = null,
    val epaisseurSideBackResult1: Int? = null,
    val epaisseurSideBackResult2: Int? = null,
    val epaisseurSideBackResult3: Int? = null,
    val epaisseurSideBackResult4: Int? = null,
    val epaisseurSideBackResult5: Int? = null,
    val epaisseurSideRightResult1: Int? = null,
    val epaisseurSideRightResult2: Int? = null,
    val epaisseurSideRightResult3: Int? = null,
    val epaisseurSideRightResult4: Int? = null,
    val epaisseurSideRightResult5: Int? = null,
    val epaisseurSideLeftResult1: Int? = null,
    val epaisseurSideLeftResult2: Int? = null,
    val epaisseurSideLeftResult3: Int? = null,
    val epaisseurSideLeftResult4: Int? = null,
    val epaisseurSideLeftResult5: Int? = null,
    val etancheiteOK1: Boolean? = null,
    val etancheiteDate1: String? = null,
    val etancheiteBar1: Float? = null,
    val etancheiteOK2: Boolean? = null,
    val etancheiteDate2: String? = null,
    val etancheiteBar2: Float? = null
)
