package com.example.myapplication.canvas

const val TITLE_IDENTIFICATION = "IDENTIFICATION"
const val SITE_DE_CONTROLE = "Site du contrôle :  ALOREM - 350 ROUTE DE THIL - D61B - 01700 BEYNOST - FRANCE"
const val PROPRIETAIRE = "Propriétaire : "
const val FABRICANT = "Fabricant : "
const val NUM_SERIE_ALO = "N° de série ALOREM : "
const val NUM_SERIE_CLIENT = "N° de série WESTERN : "
const val MARQUE_PRINCIPALE = "Marque principale : "
const val REFERENCE = "Référence: "
const val CAPACITE = "Capacité à 20°C (L) : "
const val TARE = "Tare (kg) : "
const val GROSS_MASS = "Gross Mass (kg) : "
const val MARQUES_ADDITION = "Marques additionnelles : "
const val TYPE_MATERIAU = "Type matériau : "
const val KG = "KG"
const val EPAISSEUR_PAROI = "Ep paroi min (mm) : "
const val DATE_FAB = "Date fabrication : "
const val PICTO_GERBAGE = "Pictogramme gerbage : "
const val PRESSION_MAX = "Pression max de remplissage : "

const val TITLE_INSPECTION_REGLEMENTAIRE = "INSPECTION REGLEMENTAIRE "
const val INSPECTEUR = "Personne réalisant l'inspection : "
const val DATE_INSPECTION = "Date de l'inspection : "
const val FONCTIONNEMENT_EQUIPEMENT = "Fonctionnement de l'équipement de service : "
const val ETAT_EXTERIEUR = "Etat extérieur : "
const val ETAT_INTERIEUR = "Etat intérieur : "
const val EPAISSEUR_PAROIS = "Epaisseur parois : "
const val MARQUES_REGLEMENTAIRE = "Marques réglementaires : "
const val CONFORMITE_MODELE = "Conformité au modèle type agréé : "
const val INSPECTION_REG = "inspection réglementaire : "
const val OBSERVATION = "Observation : "

const val TITLE_EPREUVE_ETANCHEITE = "EPREUVE D'ETANCHEITE A L'AIR"
const val PERSONNE_EPREUVE = "Personne réalisant l'épreuve : "
const val DATE_EPREUVE = "Date de l'épreuve : "
const val LIEU_EPREUVE = "Lieu de l'épreuve : ALOREM - 350 ROUTE DE THIL - D61B - 01700 BEYNOST - FRANCE"
const val PRESSION_APPLIQUEE = "Pression Appliquée : "
const val DUREE_EPREUVE = "Durée de l'épreuve : "
const val RESULTAT_EPREUVE = "Résultat de l'épreuve : "
const val CONCLUSION_EPREUVE = "Conclusion de l'épreuve : "

const val TITLE_CONCLUSION = "CONCLUSION DE L'ENSEMBLE DU CONTRÔLE PERIODIQUE"
const val RESULTAT = "Résultat : "
const val DATE_PROCHAIN_CONTROLE = "Date du prochain contrôle périodique : "
const val FAIT_A = "Fait à : "
const val DATE_RAPPORT = "Date du rapport : "
const val SIGNATURE_RAPPORT = "Signature du rapport (nom) : "
const val FONCTION = "Fonction : "
const val SIGNATURE = "Signature : "
